"""Added created_at timestamp to Game model

Revision ID: 9332f49fa259
Revises: 6b712510329c
Create Date: 2026-03-22 16:59:52.376001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9332f49fa259'
down_revision = '6b712510329c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
